### ISSUE TITLE
ui: inconsistent error reporting when executing action

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1015]
## Description

The user interface displays inconsistent error messages when an action fails because the data warehouse isn't connected.

## Steps to reproduce

1. Disconnect the data warehouse
2. Add a user import action to a Dummy connection
3. Click on "Run now"

Now an error is reported (and it seems correct):

![immagine](https://github.com/user-attachments/assets/1f2a1e87-2f08-4379-b4f9-b807477db745)

But clicking on the link shows this page, which does not report any error:

![immagine](https://github.com/user-attachments/assets/98bcec8f-64fd-4dfa-9503-53f6f2dc82a4)

Is this a problem of the UI, or something in the server?

**Comment by zapateo** [comment]
@gazerro, @retini, I don’t know which part of Meergo this concerns, so I don’t know which of you two wants to take a look at it.

**Comment by gazerro** [comment]
The `POST /api/workspaces/{workspace}/connections/{connection}/actions/{action}/executions` endpoint call failed, meaning no execution was created. Consequently, I don’t expect any errors to appear in the UI's Overview section.

Therefore, the UI should not display "Go to overview for details" when the execution creation has failed.

**Comment by zapateo** [comment]
This issue can no longer occur due to the fact that no warehouse is connected to the workspace (#1017). However, it is possible that there are other types of errors that could lead to this. Investigate.
