### ISSUE TITLE
ui: improve the usability of event dispatching in the UI

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1016]
Review the usability of events dispatching and importing into the data warehouse

The current way of configuring events dispatching and importing into the data warehouse can be a bit unclear (at least to me). Moreover, it does not have the flexibility to dispatch events without importing them into the data warehouse.

We should discuss this.

### Some points

* Should we create two separate actions for event dispatching and event importing? But this looks problematic as we currently represent the actions in the APIs with a tuple of Role, Connection and Target, and both those actions would be unrecognizable according to this representation. Could we address this  by adding some settings to the action?
* If I want to dispatch events to an app, there are a few different steps that need to be done, and I may miss one of them without knowing why the dispatching doesn't work. This may be resolved in some way in the UI.

**Comment by gazerro** [comment]
> Moreover, it does not have the flexibility to dispatch events without importing them into the data warehouse.

All events received from a connection source, regardless of whether they have an action or not, are processed through the actions of the connection destination to be sent to their respective apps.

If you want to save the events in the data warehouse, you need to create an action for the events in the source connection.

> The current way of configuring events dispatching and importing into the data warehouse can be a bit unclear (at least to me).

I agree. We could move the linked connections from the settings section to the actions page and provide better documentation on that page.

**Comment by retini** [comment]
@gazerro, @zapateo, as we discussed I will move the linked connections in the connection's actions page (both on sources and destinations), and I will add the same docs used by the open2b/meergo#1027 pull request.

Additionally, I will remove the linked connections from the connection creation page (both on sources and destinations).
