### ISSUE TITLE
ui: error when clicking Overview or events with event actions only

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1035]
An error occurs in the following scenarios:

* When a connection contains only actions on events, clicking the `Overview` tab triggers an error
* When a connection contains both user and event actions, the same error occurs when clicking the `Events` button on the `Overview` page.

![Screenshot 2024-09-22 at 17-58-43 Meergo](https://github.com/user-attachments/assets/82b121cc-c5cd-4952-b441-b8eba62b4c8c)

**Comment by retini** [comment]
Closed by commit 10e149c35ea4ad2f24bb9bb75acfea50b1ae4ec1.
