### ISSUE TITLE
core: error when renaming and adding properties in user schema

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1036]
When altering the user schema, if an `Object` property is renamed and a new property is added to that object simultaneously, the server responds with the error:

> cannot change the schema as specified: error on property "address" (renamed to "address2"): type changes are not supported

**Comment by zapateo** [comment]
The commit a90a2b2f2480f6a43f19a6b2f55bb2a1cd3e0fcb has resolved the issue on the server side. However, the problem still exists on the client side, in the interface.

In particular, the RePaths that the UI sends to the server are incorrect in the case where a property P1 is renamed to P2 (independently from their types), and in the same operation, a new property with the name P1 is created.

The documentation for the `Diff` function states:

https://github.com/open2b/meergo/blob/a90a2b2f2480f6a43f19a6b2f55bb2a1cd3e0fcb/apis/datastore/diffschemas/diffschemas.go#L21-L26

Consequently, referring back to the example above, the RePaths sent to the server should contain two distinct values to indicate this operation:

```json
{
    "P2": "P1",
    "P1": null
}
```

where the first line indicates that the property P1 has been renamed to P2, while the second line indicates that P1 is a new property with the name of an already existing one.

The UI currently does not behave this way, and this needs to be changed.

**Comment by retini** [comment]
The code in the UI would appear to be correct. In case of a sub-property added to a previously renamed object property, RePaths mapping from the new object property's name to the old name are correctly sent, and in the schema the renamed object property correctly contains the added sub-property.

The error would seem to occur in the server, when the renamed object property is compared with its old version and the additional sub-property is interpreted as an illegal change in the type.

**Comment by zapateo** [comment]
The commit c85b669b14adc43be0e3e6a37be47950d7e125c7 clarifies the error messages in case an attempt is made to modify a descendant property of an Object property that has been renamed, so this issue can be closed.

Then, in the issue https://github.com/open2b/meergo-rewritten/issues/1168 we discuss about the study and the addition of support for such cases.
