### ISSUE TITLE
warehouses: error when adding a column of type `Inet` to a PostgreSQL data warehouse

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1041]
When attempting to add a column of type `Inet` to a PostgreSQL data warehouse, the server returns the following error:

> cannot get the queries for the schema change: unsupported alter schema operation: the type of the column "ip_v4" is not supported by the PostgreSQL driver

However, the `Inet` type is supported by PostgreSQL, so this error seems unexpected.

**Comment by zapateo** [comment]
Since we changed the criterion following discussion, Inet type support is needed. This is tracked in https://github.com/open2b/meergo-rewritten/issues/1047, so this can be closed.
