### ISSUE TITLE
ui: problems with the page Settings > Identity Resolution

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1049]
## Problem 1/2

The buttons `Move Up` and `Move Down` don't work.

![immagine](https://github.com/user-attachments/assets/6db9fc09-2fce-4b4a-a548-319f1d0633d8)

## Problem 2/2

When saving identifiers with an empty identifier, an unclear error is shown. This is not a bug, but something that we may improve:

![immagine](https://github.com/user-attachments/assets/3a2f1e86-6d3e-4f11-9dbd-250af7275769)

**Comment by retini** [comment]
Problem 1/2 has been fixed by commit 41cb68a6d49ab26a8e951e1bd90ad1094eed192b
