### ISSUE TITLE
ui: error adding a new workspace

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1051]
Adding a new workspace, an error occurs:

![Screenshot 2024-09-27 at 16-21-29 Meergo](https://github.com/user-attachments/assets/164e812d-cfb6-4b5e-9437-69c5d766369f)

**Comment by zapateo** [comment]
This is a duplicate of https://github.com/open2b/meergo-rewritten/issues/1031, so I'm closing this.
