### ISSUE TITLE
ui: warehouse check is currently disabled during workspace creation

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#1080]
Currently the server, to perform the check of the warehouse, exposes the endpoint `/api/workspaces/{workspace}/warehouse/pings`. 

However in the UI, during the creation of a new workspace, it is not possible to call the endpoint because the workspace has not yet been created and consequently there is no workspace ID.

For this reason the button to perform the check of the warehouse in the page of the workspace creation is currently disabled.

The warehouse check can be re-enabled when a server-side method is exposed that allows the check to be performed without requiring a workspace ID.

**Comment by zapateo** [comment]
I am closing this issue as issue https://github.com/open2b/meergo-rewritten/issues/1086 has been opened, which addresses the matter, since the server-side methods necessary for the problem outlined here have been implemented.
