### ISSUE TITLE
The statistics on filtered identities are not reported or displayed correctly

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1092]
## Description

The statistics on filtered identities are not reported or displayed correctly.

## How to reproduce the issue

1. Add a Dummy source connection
2. Create an action that imports identities, and that does not import users for whom the email is `kbuessen0@example.com`
3. Execute the action
4. Open the _Analytics_ section

A count of 9 imported users apperars, but no discarded or failed users appear (instead of showing 1 discarder user).

## Causes of the issue

I have not pinpointed the cause of the issue. Does it only concern the display in the UI? Or is the problem in the statistics system? Or in the way discarded users are counted during the import?

**Comment by gazerro** [comment]
I am closing this issue in favor of issue open2b/meergo-rewritten#1099.
