### ISSUE TITLE
ui: improve the visualization of long error messages in the toast

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#1105]
Often, the UI shows the error messages returned by the server inside a toast notification.

In some cases, the returned messages are really long and this leads to a weird visualization with the toast notification covering a significant portion of the screen:

![Image](https://github.com/user-attachments/assets/caaf0b46-2878-429f-ba39-779eec522d42)

We should look for a way to improve the visualization of long error messages in the toast, for example by hiding part of the message inside an expandable accordion with a ‘see details’ button.

**Comment by gazerro** [comment]
The previous error message is not relevant as it is long, hard to read, and doesn’t get to the point. It should be:

> data warehouse cannot be initialized because the database is not empty (it contains 6 tables, 2 sequences).

@retini I don’t think we need to handle long error messages; long error messages are an issue in themselves and should be fixed rather than adjusting their display in the UI.

**Comment by retini** [comment]
@gazerro, I agree with your point of view.

I am closing this issue. If any other very long errors emerge I will point them out so that they can be improved, instead of looking for a way to deal with them at the UI level.
