### ISSUE TITLE
warehouses/snowflake: connection errors to Snowflake are hidden and connection check gets stuck

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1108]
In the Snowflake driver, in case of a connection error, the following occurs:

* (1) Errors are not reported anywhere
* (2) The connection attempt continues indefinitely

## How to reproduce the error

Enter, on the warehouse connection screen, Snowflake login credentials where the account ID, instead of being in two components separated by `-`, is made up of two components separated by a `.`.

Also see https://github.com/open2b/meergo-rewritten/issues/1109. [Fixed in commit a724204]

## Problem 1 - Errors Not Reported

Currently, connection errors to Snowflake are not displayed anywhere. It is possible to temporarily mitigate the issue by modifying the method:

https://github.com/open2b/meergo/blob/61f7369614d0f397c2657478305e3c22640b3034/warehouses/snowflake/snowflake.go#L528-L539

and adding the line at the beginning:

```go
_ = gosnowflake.GetLogger().SetLogLevel("debug")
```

to print errors to the console. However, the fact remains that this solution is not practically applicable since errors need to be clearly returned by the APIs and reported to the user using the UI.

## Problem 2 - Infinite Connection Attempts

It seems that the Snowflake driver, in case of a connection error, continues to attempt to connect indefinitely. In particular, this occurs within the `execute` method:

https://github.com/open2b/meergo/blob/681f86e6e8d87ad569ebb81b2288874415ea95f0/vendor/github.com/snowflakedb/gosnowflake/retry.go#L297

**Comment by gazerro** [comment]
@zapateo I wasn't able to reproduce these issues. Could you try again and let me know how to reproduce them?

**Comment by zapateo** [comment]
This problem no longer occurs as it has been "hidden" by the commit that introduced this check:

https://github.com/open2b/meergo/blob/91f5e832be78d04aa256099538b10c1617590ffc/warehouses/snowflake/warehouse.go#L72-L74

As a result, it no longer makes sense to keep the issue open, because there seems to be no way to reproduce it. If later on, other combinations of user input arise that can cause infinite waits without feedback for the user, we will reopen the issue.
