### ISSUE TITLE
warehouses/snowflake: the format of the account ID copied from the Snowflake site is incorrect in Meergo

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1109]
The format of the account ID copied from the Snowflake site is incorrect in Meergo.

### How to copy the account ID from the Snowflake site

From the Snowflake site interface, you can copy the account ID as follows:

1. User button at the bottom
2. Hover over Account
3. Hover over the account you want to connect
4. Click the "Copy account identifier" button

### The problem

The copied account ID has the format:

```
XXXXX.XXXXX
```

but the format that needs to be entered in the Meergo UI form has the two components separated by a hyphen:

```
XXXXX-XXXXX
```

Entering the ID in this format does not display any error indicating the problem.

### Considerations

This is a usability issue, as it would be sufficient to document this. However, it can be inconvenient, and it may be worth investigating how to handle this differently.

Is something needed in the UI? A check, or simple documentation? Or is it a change to be made on the server side?

Or should the UI accept the format copied from the Snowflake site, and then have the server handle it? Or, in other places, is the copied format actually the one required by the Meergo UI, and therefore the inconsistency lies with the Snowflake site?

We need to clarify the situation.

Additionally, since the problem mentioned in issue https://github.com/open2b/meergo-rewritten/issues/1108 also occurs, the usability issue is greater.

**Comment by gazerro** [comment]
The following documentation is relevant:: https://docs.snowflake.com/en/user-guide/admin-account-identifier

Account identifiers come in two forms:

* `<orgname>-<account_name>` for most URLs and general use cases, including Snowflake drivers, and for scenarios/features where underscores in an account name are not supported.
* `<orgname>.<account_name>` for SQL commands and operations.

In our case, the user who enters their account identifier should not be concerned with which form is used and should not have to choose between the two formats. Both forms should be accepted, and the hyphenated form should be used for the connection.
