### ISSUE TITLE
apis: unexpected error when creating an "Export users" action on a Filestorage connection

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#1118]
Currently, when you create an “Export users” action on a Filestorage connection and also pass filters, you get the following error returned by the server:

![Image](https://github.com/user-attachments/assets/96690da2-17c4-4807-8dfd-6225f0c52315)

This error occurs, precisely, only when you also pass filters, whereas if you do not pass any filters the action is successfully saved.

The error would seem to be about the fact that the UI is passing the entire user schema into the action, even though some of the properties are not actually used by the action itself.

However, from the documentation in [actions.csv](https://github.com/open2b/meergo/blob/main/core/Actions.csv), it would appear that sending the entire user schema is the correct behavior in the UI.

**Comment by gazerro** [comment]
Fixed in commit d92a8a0.
