### ISSUE TITLE
ui: warehouse mode is empty when opening data warehouse settings page

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1125]
Warehouse mode is empty when opening data warehouse settings page.

## How to reproduce

* Initialize a workspace (for example via meergo cli)
* Click on Customization > Data Warehouse

Now, instead of seeing the current warehouse mode, a blank select is shown.

## Screenshot

![Image](https://github.com/user-attachments/assets/7dd4a4da-81c2-43b3-8dd3-c464e6b57da8)

**Comment by retini** [comment]
This is a Shoelace issue. We must track [Shoelace issue 2254](https://github.com/shoelace-style/shoelace/issues/2254) and update the package when the issue is fixed.
