### ISSUE TITLE
connectors: Internal Server Error when adding an action to a MySQL connector, if the query contains a not valid property name

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1147]
## Description

Internal Server Error when adding an action to a MySQL connector, if the query is written as follows:

```sql
SELECT 1
WHERE ${last_change_time}
LIMIT ${limit}
```

I don't know what causes this error, nor if it is broader and applies to other connectors. I haven't investigated it yet.

## How to reproduce

1. Add a MySQL source connector
   
2. Open the user import action addition screen

3. Add a query written as follows:

   ```
   SELECT 1
   WHERE ${last_change_time}
   LIMIT ${limit}
   ```

4. Click on "Confirm"

An internal server error is returned to the client and an error is logged.

## Error reported in the log

```
time=2024-11-18T14:39:05.702+01:00 level=ERROR msg="error occurred serving Core" err="the 1st column has an invalid name: \"1\". Column names must start with a letter or underscore [A-Za-z_] and subsequently contain only letters, numbers, or underscores [A-Za-z0-9_]"
```

**Comment by gazerro** [comment]
@zapateo The error is caused by the column name `1` returned by the connector, which is not a valid property name. Commit e3cf69f returns the error as a `503 Unavailable Error` error instead of a `500 Internal Server Error.`

This query does not return an error:

```sql
SELECT 1 as one
WHERE ${last_change_time}
LIMIT ${limit}

```
