### ISSUE TITLE
ui: should property names be rendered with monospaced font?

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#1185]
## Description

Currently, property names in the interface, across different pages, are often rendered with proportional fonts.

I propose using monospaced fonts for two reasons:

* Aesthetic reason, because identifiers are generally represented with monospaced fonts.
* Readability reason, because some characters used in identifiers can be easily confused with one another (see screenshot below).

For now, I will mark this issue as a Release Blocker. We should perhaps discuss it and evaluate if these changes make sense and possibly which ones to implement before the release.

## Some pages that use the proportional font

* Action's editing page, in the Mappings section
* User Profiles
* Customization > Customer Model
* Other pages?

## Some Screenshots

Customer model (current font family):

![Image](https://github.com/user-attachments/assets/b26d5a0c-edce-40ce-99af-c4559210cb35)

Customer model (with monospaced font, which better distinguishes the characters `O`, `o`, and `0`, `I`, `l`, and `i`):

![Image](https://github.com/user-attachments/assets/f446fafc-4dd0-480f-928f-0c3e71bc066c)

**Comment by zapateo** [comment]
@gazerro, @retini, let me know what you think about this.

**Comment by gazerro** [comment]
I don’t expect the name of a property to be designed in such a way that it looks awkward or difficult to read unless displayed with a monospaced font. The examples you chose do not occur in real-world scenarios.

If readability were truly an issue for property names, why wouldn’t the same problem apply to any other text, apart from predefined and well-known values?

In my opinion, context determines whether readability is an essential characteristic. For instance, if the context in which the name is displayed assumes that the user will need to write it—such as in transformations—it might make sense to display it in monospace. Displaying it in monospace, unlike other text, also suggests that this is the specific text the user is expected to write, not something else.

Conversely, in cases like viewing a list of user properties with their respective values, I wouldn’t expect or desire the property names to be in monospace while the values are not.

**Comment by zapateo** [comment]
> I don’t expect the name of a property to be designed in such a way that it looks awkward or difficult to read unless displayed with a monospaced font. The examples you chose do not occur in real-world scenarios.

Since we do not know precisely the uses of properties and what they could be used in real scenarios, I put myself in the most generic perspective possible. For this reason, in the examples, I have shown examples of cases that yes, appear unreal at the moment, but that I do not feel like excluding as a typology of property names in general.

In any case, I agree with what you say here (also following the various discussions in person):

> In my opinion, context determines whether readability is an essential characteristic.

So the problem needs to be addressed individually at each point, so I close this issue.
