### ISSUE TITLE
ui: error "Matching properties cannot be empty" when opening testing mode without a mapping

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#1209]
When adding an action, clicking on "Testing mode" immediately without first entering a property in the mapping results in the error: "Matching properties cannot be empty."

However, I expect the testing mode to always be accessible, even in case of errors.

**Comment by retini** [comment]
@gazerro, after our discussion last Friday about improving the handling of cases where a user attempts to open the testing mode without entering matching properties first, should we consider this issue closed?

**Comment by gazerro** [comment]
@retini from the latest changes, it looks like the issue has been resolved, so I’m closing it.
