### ISSUE TITLE
proposal: export: configure a destination storage to disable file truncation

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#168]
Currently, when exporting to a file, it gets truncated if it already exists.

It's not necessarily the desired behavior at all times, so it **should be possible to configure the action** (or the connection) **so that the file is only updated if it's new** (i.e. it never gets truncated); otherwise, an error should be returned or, alternatively, no operation should be performed.

**Comment by gazerro** [comment]
@zapateo do you know in more detail what this issue refers to?

**Comment by zapateo** [comment]
> @zapateo do you know in more detail what this issue refers to?

I updated the body of the issue by adding more details.

**Comment by zapateo** [comment]
This proposal makes no sense because storages should guarantee atomicity; if they don't, for some implementative reason, they should expose a specific-setting to handle this. This should not be handled by Chichi, so this PR can be closed.
