### ISSUE TITLE
tracker: riscrivere lo script di tracking

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#17]
Lo script di tracking deve essere riscritto tenendo conto delle seguenti considerazioni:

* deve inviare gli eventi alla stessa origine dell'URL dello script 
* deve inviare il prima possibile l'evento di visita della pagina
* non deve espostare nomi globali
* non deve avere la property codificata nel codice ma la deve leggere ad esempio da una variablie globale
* deve verificare che `localStorage` sia leggibile e non deve alzare un'eccezione nel caso in cui non lo sia
*  non deve chiamare `navigator.geolocation` in quanto il browser chiederebbe conferma all'utente
* non deve leggere l'oriario dal browser in quanto la data del computer dell'utente non è affidabile
* non deve chiamare `navigator.userAgentData.platform` in quanto deprecato
* deve scrivere sulla console solo in caso di errore
* il click deve essere tracciato su qualsiasi elemento che sia un link o che visivamente sia un pulsante

**Comment by retini** [comment]
**deve inviare gli eventi alla stessa origine dell'URL dello script**
L'URL viene adesso recuperata dall'attributo `src` dello script tag.

**deve inviare il prima possibile l'evento di visita della pagina**
L'evento `pageView` viene inviato come prima cosa durante l'esecuzione dello script. É possibile inserire il tag `script` dentro all'`head` del documento HTML (dopo il `title`) per fare in modo che l'esecuzione avvenga ancor prima del caricamento della pagina.

**non deve espostare nomi globali**
Il codice dello script è stato racchiuso in una `IIFE`.

**non deve avere la property codificata nel codice ma la deve leggere ad esempio da una variablie globale**
La property viene adesso recuperata dall'attributo `data-property` dello script tag.

**deve verificare che localStorage sia leggibile e non deve alzare un'eccezione nel caso in cui non lo sia**
É stata implementata la funzione `isStorageAvailable`, secondo le indicazioni di MDN Web Docs [(Testing for availability)](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#testing_for_availability)

**non deve chiamare navigator.geolocation in quanto il browser chiederebbe conferma all'utente**
`navigator.geolocation` è stato rimosso

**non deve leggere l'oriario dal browser in quanto la data del computer dell'utente non è affidabile**
L'orario del browser è stato rimosso

**non deve chiamare navigator.userAgentData.platform in quanto deprecato**
`navigator.userAgentData.platform` è stato rimosso.

**deve scrivere sulla console solo in caso di errore**
Adesso lo script scrive nella console solo in caso di errore

**il click deve essere tracciato su qualsiasi elemento che sia un link o che visivamente sia un pulsante**
Adesso il click viene ascoltato su tutti gli elementi `a, button, input[type="submit"]`.  É stata implementata una funzione `sendClickEvent` che raccoglie i dati giusti in base al tipo di elemento cliccato. Questa nuova funzionalità può essere testata nel sito di test in `trace-events-script/website-for-testing`, il quale è stato esteso.

**Comment by retini** [comment]
Done with commit 38011f7fc3ff5707021e518d689ab08b58bd7f5e.

**Comment by gazerro** [comment]
This issue is deprecated, so close it.
