### ISSUE TITLE
In the UI, use the component used in mappings for choosing the properties in the matching section when exporting to apps

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#170]
This component:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/f5c4a07f-d011-4eee-9f7d-a6e3b72e9db9)

should be used instead of this simple text input:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/9b704b1a-bfca-410d-b7aa-a76a485a1594)

**Comment by retini** [comment]
Commit 6922772 carries out the changes requested by this issue
