### ISSUE TITLE
export: allow in apps limiting users to the ones updated or created since last export

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#172]
We may use a solution similar to the files: open2b/meergo-rewritten#166.

**Comment by zapateo** [comment]
This is related to the concept of _re-export_:

* what does it mean?
* is it necessary?
* may be implicitly implemented using a solution proposed in the issue open2b/meergo-rewritten#166?

**Comment by zapateo** [comment]
After a discussion with @gazerro, we decided that is necessary that app's export should always work in incremental mode. The case when a user wants to re-export everything can be handled by creating a new action.

**Comment by gazerro** [comment]
See commit 59c5670.
