### ISSUE TITLE
export: review behavior of export users to apps in case of multiple matchings (both internal and external)

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#175]
When exporting to an app which has these users:

| External ID | Email             |
|-------------|-------------------|
| 111         | mario@example.com |
| 222         | mario@example.com |

if the external property `Email` has been choosed for matching, it's impossibile to Meergo to identify an unique user. We should handle this, maybe throwing an error.

**Comment by zapateo** [comment]
After a discussion with @gazerro, we decided that it is reasonable to return an error.

**Comment by zapateo** [comment]
At the moment, the `DestinationUser` method, implemented by the data warehouse, internally handles the error.

So:

* The error is already returned in the case where multiple users match.
* Outside of the data warehouse, there is no information available about the error.

Therefore, the modification discussed in this issue is only partially implemented. The data warehouse interface needs to be reviewed to return specific error information or return zero, one or more users and let the caller find and handle the error.

**Comment by gazerro** [comment]
See pull request open2b/meergo#447.

**Comment by zapateo** [comment]
I can confirm that this issue still applies.

When a user to export matches with more than one user on the destination app, the export action fails with error:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/42a232d2-5f36-41df-baee-bd69f19581d1)

while the log contains this:

```
time=2024-02-20T10:30:57.093+01:00 level=ERROR msg="cannot execute action" action=784460497 execution=12 err="data warehouse error: too many users matching when using property"
```

**Comment by zapateo** [comment]
After a discusion with @gazerro, we decided that:

there are 4 cases that can occur (internal users matching $\times$ external users matching):

* $1 \times 1$
* $1 \times m$
* $n \times 1$
* $n \times m$

The first case, $1 \times 1$, is the normal one.

The last two, where more Meergo users can correspond to one (or more) app users, are managed by performing a check before exporting and in that case blocking everything.

The case $1 \times m$ is handled by allowing the user to choose through an option:

* which is at the action level
* which is not selected by default
* which allows choosing something like: *export the user anyway in case of a match with multiple users on the app*

**Comment by zapateo** [comment]
After a discussion with @gazerro:

### External User Check

* ~~If a user in Meergo corresponds to multiple users in the app (case $1 \times m$), then initiate or not initiate the export based on the setting in the action (in case of initiation, obviously overwriting all users)~~
* If there are multiple users in the app with the same value for the external matching property, then initiate or not initiate the export based on the setting in the action; in the case where the export is initiated, it means that all "duplicate" users in the app will be overwritten.
* The label on the option in the UI should indicate that the check pertains to users present in the app, not those to whom I will export.

### Internal User Check

* If multiple users on Meergo have the same value for the same internal matching property (thus both cases $n \times 1$ and $n \times m$), do not initiate the export.
* Perform this check through an ad-hoc method in the data warehouse, which also returns useful information to resolve the problem; for example, the method could be something that returns duplicated users.
