### ISSUE TITLE
ui: distinguishing between source and destination using the `HasUI` field

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#178]
The `HasUI` field in the API tells us if a connector has UI. But when either the source or destination connector doesn't have UI, the UI shows an empty interface.

**Comment by gazerro** [comment]
@retini has this issue already been resolved?

**Comment by retini** [comment]
@gazerro, I add the following notes after our discussion on the issue.

The issue doesn't directly concern the UI but the way the `HasUI` field is handled server-side.

In practice, if a connector implements the `ServeUI` method but provides UI components only for the sources, the `HasUI` field is still set to `true`.

This means that the destinations of that connector will have the `HasUI` field set to `true` even if they actually have no components to display, leading to UI-related issues.

A change should be made to make the `HasUI` field more specific, for example by splitting it into `HasSourceUI` and `HasDestinationUI`.

**Comment by gazerro** [comment]
When a connector implements the `ServeUI` method, it doesn't guarantee the method will return a field. A connector can opt not to return a field, even if it implements `ServeUI`. Consequently, the UI shouldn't rely solely on the `HasUI` flag; rather, it should verify that the call to `ServeUI` indeed returns fields.

To streamline the UI code, I suggest ensuring that any call to `ServeUI` returns `nil` if there are no fields.
