### ISSUE TITLE
Connection users and destinations users should be removed when a connection / action is removed

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#179]
Connection users and destinations users should be removed when a connection / action is removed.

Since we can't do this in a single transaction (such tables belongs to the data warehouse database) we should implement a procedure that periodically cleans the tables.

**Comment by gazerro** [comment]
@zapateo can you review this issue?

**Comment by zapateo** [comment]
> @zapateo can you review this issue?

This issue is obsolete since it refers to the old implementation of the identity resolution. Closing.
