### ISSUE TITLE
ui: user table is not updated when a new column is added

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#181]
When adding a new column to the Golden Record of users, the table in 'admin/users' page is not updated.

Also, it does not appear in the list of columns in the <kbd>Toggle column</kbd> menu.

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/f7e146bc-8c9b-4d5e-bc8d-85180c5db294)

It is necessary to manually delete the local storage of the browser.

We may force the reloading of the properties every time this page is loaded as a workaround, for now, until this part is properly implemented.

@gazerro what do you think?

**Comment by gazerro** [comment]
The UI could call the `schema` method on the workspace to retrieve the user schema and then update the list of columns if necessary.

**Comment by zapateo** [comment]
Also see the issue https://github.com/open2b/chichi/issues/319, which seems to be caused by this issue.
