### ISSUE TITLE
mapping: the current implementation of transformation functions is extremely slow

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#185]
We should find a way to speed up transformations of users / events .., because the current implementation tooks too much time.

We could, for example, launch a single instance of the Python VM for every import/export operation, and pass a batch of users instead of a single user to the transformation function.

**Comment by zapateo** [comment]
Take a look at this: https://github.com/open2b/chichi/issues/234.

**Comment by gazerro** [comment]
@zapateo can this issue be closed?

**Comment by zapateo** [comment]
> @zapateo can this issue be closed?

Yes.
