### ISSUE TITLE
Support sending events to apps that authorize using OAuth

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#187]
Currently, the OAuth access token is not provided to the opened app connection, so the events can only be sent to connectors that use a different authorization mechanism. We have to implement a way to retrieve - and maintain up-to-date - the OAuth parameters.

See this code:

https://github.com/open2b/meergo/blob/8c6d636ce603be6e9abb4e54e657d236c6ebd0b0/apis/events/state.go#L225-L248

**Comment by zapateo** [comment]
@gazerro can this be fixed with the last changes you made to OAuth, or is this something different?

**Comment by gazerro** [comment]
> @gazerro can this be fixed with the last changes you made to OAuth, or is this something different?

No, it's actually different. The `openDestination` method could refresh the access token, just like we do in other situations. But it would be better to wait for an HTTP mechanism that automatically handles the access token refresh.
