### ISSUE TITLE
Review the handling of the DateTime layout, all across the code

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#202]
We should review the handling of the layouts of the DateTime types.Types.

In particular, if the layout is not empty then it means that the time should be represented by a string in Go; otherwise, if it's empty, we expect the Go type to be a `time.Time`.

We should formalize this criterion and special cases, then review the handling of the layouts and DateTimes in Meergo.

**Comment by gazerro** [comment]
Note that

* the layout applies to `DateTime` and `Date` types,
* the canonical value for a `DateTime` is a `time.Time` in UTC with year in range [1, 9999],
* the canonical value for a `Date` is a `time.Time` in UTC with zero time fields with year in range [1, 9999].

Code to check:

* [x] App normalization
* [x] Database and file normalization
* [x] Mapping
