### ISSUE TITLE
Implement the TypeScript type checking / build infrastructure

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#239]
Some notes after the discussion with @retini on jul 31th, 2023:

* add a `tsconfig.json` file under `admin`, which will contain the configuration for our TypeScript project as well as build options
* install the `tsc` command as a dev-dependency for the admin, which will be used by the `go run commit/commit.go` script
* change the `go run commit/commit.go` script to run the `tsc` TypeScript compiler against `admin/tsconfig.json`
* the TypeScript files will be transpiled to JS on demand by EsBuild, while `tsc` will handle the type checking of the `.ts` files in the repository
* tsc should not transpile code, only check if code is correct. To do so, we may investigate if the `--noEmit` option may be useful.

```mermaid
flowchart LR
    esbuild["ESBuild"]
    ts_files["TypeScript <code>*.ts</code> files"]
    tsc["The <code>tsc</code> command"]

    esbuild <-- TypeScript to JavaScript --> ts_files
    ts_files <-- type checking --> tsc
```

**Comment by retini** [comment]
Additional note after discussion with @gazerro and @zapateo on aug 12th, 2023:
- We can evaluate whether to use Deno to do type checking and bundling (see [Deno's Typescript Overview](https://deno.land/manual@v1.36.4/advanced/typescript/overview))
