### ISSUE TITLE
all: update to Go 1.21

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#251]
* [x] update Go version in the `go.mod` files.
* [x] use the `slices` package of the standard library instead of the `golang.org/x/exp/slices` package.
* [x] use the `slices.Sort` function instead of the `sort.Strings` function.
* [x] ~use the `maps` package of the standard library instead of the `golang.org/x/exp/maps` package. Note that `Keys` and `Values` functions are not present in the standard library.~
* [ ] use the `slog` package instead of the `log` package for logging.
* [x] ~use the `slices.SortFunc` function instead of the `sort.Slice` function.~

**Comment by gazerro** [comment]
> use the `slices.SortFunc` function instead of the `sort.Slice` function.

`slices.SortFunc` uses a comparison function rather than a less function, therefore the `sort.Slice` function is easier to use, while `slices.SortFunc` is more efficient. However, since the usage we have doesn't appear to demand this greater efficiency, I would leave the code as it is.

**Comment by gazerro** [comment]
> use the `maps` package of the standard library instead of the `golang.org/x/exp/maps package`. Note that `Keys` and `Values` functions are not present in the standard library.

Apart from the `Keys` and `Values` functions, we only make use of the `Clone` and `Equal` functions. However, in order to use them, we would need to import two different packages with the same name. Therefore, we will postpone this modification until version 1.22 of Go.

**Comment by gazerro** [comment]
Commit 5cb9376 has replaced the `log` package with the `slog` package.

**Comment by zapateo** [comment]
> Commit [5cb9376](https://github.com/open2b/chichi/commit/5cb937698d935e486fd1d066e5fe5ba30f98e5d1) has replaced the `log` package with the `slog` package.

So, can we close this issue?

**Comment by gazerro** [comment]
> So, can we close this issue?

No. `log` is currently used in chichi-cli.

**Comment by zapateo** [comment]
@gazerro, since we already have the Go version 1.22 in Chichi and this issue seems to be obsolete from the title, what about opening a more specific issue about the replacement of `log` with `slog`, closing this?

**Comment by zapateo** [comment]
Opened the issue https://github.com/open2b/chichi/issues/651, closing this.
