### ISSUE TITLE
Arrays are not rendered correctly in the users' table in the UI

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#268]
Array values are rendered correctly in the user's trait page:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/3083d2d2-f604-48d5-9a49-f5bd87996b7e)

while are not rendered correctly in the users' table:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/9f3757d5-e47a-4a3f-b0f7-c28d50bc6c16)

**Comment by retini** [comment]
Closed with commit [3f60c53](https://github.com/open2b/chichi/commit/3f60c5307733a4402bd2ecb9df94da4f6da785b5)
