### ISSUE TITLE
events: send events to ClickHouse when the process terminates

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#28]
We need to manage the process shutdown signal to interrupt event reception and send the events not yet delivered to ClickHouse to prevent them from being lost.

**Comment by zapateo** [comment]
@gazerroo, does this issue still have something useful for which it needs to remain open, or can it be closed?

**Comment by gazerro** [comment]
@zapateo Can be closed. The issue is broader and not just related to ClickHouse, so for now, I would close this issue.
