### ISSUE TITLE
ui: error mapping to anonymous identifiers in an action

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#286]
The screen of an action, in the identifier section, allows you to associate a property with an anonymous identifier:

![errore-identificatori](https://github.com/open2b/meergo-rewritten/assets/891354/30a5a286-4df7-4162-8da6-30b6197fbcb3)

As a result, when adding the action, the server responds with an unprocessable error with code `MappingOverAnonymousIdentifier`.

User properties used as anonymous identifiers should not be present in the identifier selection menu.

**Comment by retini** [comment]
This was closed by commit [#5457c71](https://github.com/open2b/chichi/commit/5457c71f81b1843ed4ef83dc3764a8befd3d98bc)
