### ISSUE TITLE
Pass the language-specific type values to the transformation functions

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#290]
Pass the language-specific type values to the transformation functions.

For example, we should pass `datetime.datetime` values to the Python transformation functions instead of simply passing `str` values.

This requires a review of the physical types, and how every of them should be passed to Python and Javascript.

**Comment by zapateo** [comment]
@gazerro this is solved, isn't it?

**Comment by gazerro** [comment]
Resolved by commit 3611efd and 53c9766.
