### ISSUE TITLE
ui: review the meaning of the connections' stats

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#293]
Review the method `updateConnectionsStats`

https://github.com/open2b/meergo/blob/aac36b8375d94bfc8b6ad6938c50d814a107fff8/apis/connection.go#L2024-L2032

Is this method still required? Which stats should be updated?

**Comment by zapateo** [comment]
The commit f0c16aa made some changes to the stats, but the question of this issue remains opened.

Also, as you may see in the description of the commit f0c16aa, the variable names in the UI must be reviewed.

**Comment by gazerro** [comment]
Note that commit 6088645 has removed the `updateConnectionsStats` method.

**Comment by gazerro** [comment]
I am closing this issue in favor of issue open2b/meergo-rewritten#929, considering that the `updateConnectionsStats` method no longer exists.
