### ISSUE TITLE
proposal: connector/types: consider replacing the decimal module with the decimal128 module

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#306]
The module [github.com/woodsbury/decimal128](https://github.com/woodsbury/decimal128) implements a `decimal128.Decimal` type. In comparison to the `decimal.Decimal` type, it has the following features:

* Precision is limited to 34 (?) digits instead of the precision of a `*big.Int`.
* A decimal requires two `int64` values instead of a `*big.Int` and an `int32`.
* It implements the `Append` method to append a `decimal` to a `[]byte`. Currently we use `MasrhalText` that allocates.
* Supports NaN and ±Inf.

Using `decimal128.Decimal` would make the usage of decimals more efficient at the cost of reduced precision, but see [precisione dei database](https://github.com/open2b/chichi-docs/blob/main/Data%20types.md).

**Comment by zapateo** [comment]
After a discussion with @gazerro, we have noticed that the decimal128 package is not documented, and it's unclear what precision it supports. Without this information, we are unable to determine if it meets Chichi's requirements.

**Comment by gazerro** [comment]
Close because the precision is too low to be used for decimal types of data warehouses.
