### ISSUE TITLE
ui: add a default query to the database action creation page

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#316]
We should **include a default query in the database action creation page**.

The query should look something like this:

```sql
SELECT id, timestamp FROM table LIMIT ${limit}
```

and may include some comments on how to modify it.

Please note that **the query syntax depends on the database**, so it should be the responsibility of the database connector to expose the query or the necessary information to construct it. Therefore, **this change involves both the UI and the connector code**.

**Comment by gazerro** [comment]
Commit 5acc7dd has prefilled the action query.
