### ISSUE TITLE
proposal: import: change the syntax of "limit" in queries and placeholders in paths

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#317]
## Limit in queries

Currently, the format of the "limit" in import queries is:

```sql
SELECT * FROM accounts {{ LIMIT $limit }}
```

However, this format doesn't provide any known advantages and doesn't offer greater flexibility. We should modify the syntax to be more restrictive but simpler, making it more straightforward and less prone to errors, something like:

```sql
SELECT * FROM accounts LIMIT $limit$
```

This clearly means that the "limit" must always be present. In cases where a query needs to return an "unlimited" set of values, it should be Chichi's responsibility to set a reasonably high limit. What should this limit be? It's possible that the connector should expose this information.

## Placeholders in file export paths

We should find a solution which is compatible also with the placeholders in file export paths, to increase the coherence in the user experience.

**Comment by gazerro** [comment]
As discussed with @zapateo , we will use the syntax:

```sql
SELECT * FROM accounts LIMIT ${limit}
```
