### ISSUE TITLE
import: handle IDs and timestamps when importing from files

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#331]
After a discussion with @gazerro, we decided that:

* The user **must** choose a property for the ID. The UI may suggest a property named "id" or the first property.
* The user **may** choose a property for the timestamp. The UI may suggest a property named "timestamp".
* The user does not choose a property by its name or by its label; he simply chooses a property.
* The source file actions should expose on the APIs two fields `IdentityProperty string` (which must always be set) and a `TimestampProperty string`

**Comment by zapateo** [comment]
For the UI:

![Senza titolo-2023-10-23-1610](https://github.com/open2b/meergo-rewritten/assets/11294400/e7114b16-3138-47b0-b8c7-0ab5003f8453)

**Comment by retini** [comment]
After discussion with @zapateo, we have decided to leave empty the field indicating the identifier of the source file, if there is no column named "id". In this way, we force the user to manually insert the correct file's column and prevent the use of potentially incorrect columns as IDs. Eventually, we might implement the behavior defined in the mockup during usage, should we realize that it is indeed the most convenient and typical behavior.

**Comment by zapateo** [comment]
@retini note that the `IDProperty` field has been renamed to `IdentityProperty`.

**Comment by zapateo** [comment]
@retini 

![Senza titolo-2023-10-25-0939](https://github.com/open2b/meergo-rewritten/assets/11294400/fad9019f-05f2-46e3-b8d1-8994a06ab2f6)

I would add as possibile values for the format:

* `2006-01-02 15:04:05` (which is the more common)
* `2006-01-02T15:04:05Z07:00` (which is RFC3339) 
* `2006-01-02T15:04:05.999999999Z07:00` (which is RFC3339 with nanoseconds)
* also, if possible and easy to do, it would be nice to let the user customize the format

The field of `ActionToSet` is called `TimestampFormat`, and must be passed to the APIs only when `TimestampProperty` is not empty.

**Comment by retini** [comment]
To make the new "with format" field customizable, we can try using the `ComboBoxInput`
