### ISSUE TITLE
import: investigate on how to handle record / rows / users with errors during import

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#333]
How should we handle these cases?

* Error while importing a single record from a file
* Error while importing a row from a database
* Error while importing a user from an app

Should it only fail that specific line, or should the error abort the entire execution of the action?

**Comment by gazerro** [comment]
Before the commit da295d9, in the event of an error during the import of a record, the import process would fail, and subsequent records were not imported. With the da295d9 commit, on the other hand, in case of an error with a record, in most situations, the record is not imported, but the import process continues with the subsequent records. This applies to both apps and databases, as well as files.
