### ISSUE TITLE
ui: improve settings usability of connections

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#340]
The settings section of each connection in the UI has some usability issues, and this issue aims to address them.

Some issues identified are:

* It is not possible to rename a connection's name.
* It is not possible to change the compression of a file connector.
* The "Enabling" and "Deletion" sections are too specific to warrant their own section.

I propose having an initial section called "General," which allows for the following:

* Renaming the connection's name.
* Enabling or disabling the connection.
* Deleting the connection.
* Changing, adding, or removing storage if the connection has one.
* Changing the compression, if the connection is a file.

For website connections, there will be a setting called "Snippet." to copy the website snippet.

Following this, there will be another section dedicated to the connector's settings, named "App Settings," "Database Settings," etc., depending on the type of connection.

For connections that have keys, there will be another setting called "API Keys."

**Comment by retini** [comment]
After a discussion with @gazerro and @zapateo, we decided to also review the design of the page, aligning the settings more closely with the upper left part of the page, bringing the various vertical tabs closer together, and slightly shrinking the form controls.

Branch is `set-connection`.
