### ISSUE TITLE
proposal: import: make importing a compressed file more intuitive

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#349]
When specifying that files are compressed in a connection file, the following rules apply:

- Files in storage must necessarily have the extension ".zip," ".gzip," or ".snappy" based on the indicated compression. For example, "users.csv.zip."
- You should specify the filename in the action without the extension as the file name. For example, "users.csv."
- In the case of Zip archives, the file within the compressed file must have the path as indicated in the action. For example, "users.csv."

These rules are not intuitive and rather restrictive. I propose to change them as follows:

- Files in storage can have any name, with or without an extension, and with any extension.
- The filename in the action must exactly match the filename in storage.
- In the case of Zip archives, there must exist a single file within the archive with any name, and this is the file to be imported.

The first two rules also apply to exports. Additionally, for exports, the path name in an archive is obtained by removing the extension from the file specified in the action, if it is present.

**Comment by zapateo** [comment]
After a discussion with @gazerro, this change seems right to me.
