### ISSUE TITLE
connectors: passing empty settings to a connector with settings returns HTTP error with `"unexpected end of JSON input`

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#355]
Is this related to the implementation of the connectors? Or it depends on Chichi?

## Steps to reproduce

1. Add a connector that has settings, for example Dummy
2. Call the APIs via HTTP not providing the `Settings` field when creating the connection

The server returns:

```
unexpected HTTP status code 422: {"error":{"code":"InvalidSettings","message":"settings are not valid: unexpected end of JSON input","cause":"unexpected end of JSON input"}}
```

Is this intended?

**Comment by gazerro** [comment]
@zapateo does pull request open2b/meergo#459 resolve this issue?

**Comment by zapateo** [comment]
> @zapateo does pull request open2b/meergo#459 resolve this issue?

Yes, it does, since it returns a clear error message instead of returning `unexpected end of JSON input`, which is weird and obscure.
