### ISSUE TITLE
ui: no overview for destination connections

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#358]
## Steps to reproduce

1. Create a destination connection
2. Create an action on it
3. Run it
4. Go to the Overview tab

Instead of seeing and overview of the export - and eventual errors, - nothing is shown instead.

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/2f2cb978-facd-4b2d-a074-ad967518d1b0)

**Comment by retini** [comment]
Closed by commit [admin: show the executions list of the destination connections](https://github.com/open2b/chichi/commit/8e07aec5b5d44e209f2f81e09f9eff8fce3c83c8)
