### ISSUE TITLE
connectors: ensure that storage connectors operations are atomic

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#359]
| Connector  | State     |
| ---------- | --------- |
| Filesystem | Done in 0e50bf5a4125d773a67ca8460c2fa69e692bfa6f |
| HTTP       | This should be guaranteed by the server that receives the POST request |
| S3         | This should be already guaranteed by the `PutObject` method of S3 |
| SFTP       | `Write` is not atomic. See issue open2b/meergo-rewritten#463. |

**Comment by gazerro** [comment]
Close this issue in favor of issue open2b/meergo-rewritten#463.
