### ISSUE TITLE
connectors: investigate if the Snowflake connector returns correct information about nullable columns

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#374]
The PostgreSQL connector does not return any information about nullability of columns:

https://github.com/open2b/meergo/blob/3640948bf7e8428607867c8592ee2e7210452c57/connectors/postgresql/postgresql.go#L135-L137

while the MySQL driver does:

https://github.com/open2b/meergo/blob/17d7a1d92e432e54628c8076f4dc350a555cc43c/connectors/mysql/mysql.go#L276-L283

How does the Snowflake driver behave?

* [x] check if the method `Columns` returns the correct value for the `Nullable` field
* [x] check if the method `Query` returns the correct value for the `Nullable` field

**Comment by gazerro** [comment]
Note that for constant columns, as in the query `SELECT TRUE, 1, 1.1, "foo"`, the `Columns` and `Query` methods return `Nullable` set to `true`.
