### ISSUE TITLE
import: internal error importing users if a user property is nullable

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#385]
If the `users_identities` schema includes a nullable property, and the importing users lack a value for that property due to its absence in the input schema, an internal error will occur:

> data warehouse error: ERROR: relation "destinations_users" does not exist (SQLSTATE 42P01)

**Comment by zapateo** [comment]
This appears to be one of several issues that arise because no validation of values is performed before sending them to the data warehouse.

Therefore, this issue can be closed in favor of https://github.com/open2b/chichi/issues/394.
