### ISSUE TITLE
apis: review the functioning of the `order` parameter passed to `(*Workspace).Users` method

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#408]
We should review and possibly correct the functioning of the "order" parameter passed to the API method that retrieves users.

## Details

* Can it be an empty string, meaning a default? If so, who handles it? Which property can be used in such a case?
* Is the parameter functioning correctly? It seems that even when, for example, "email" is passed after importing users from Dummy, the `Users` method still returns the users in a different order.
* Do we also have the "order" parameter for other methods, like on events? Investigate.

**Comment by gazerro** [comment]
@zapateo As the method always returns a limited number of users, meaning it may not return all of them, if the caller does not specify an ordering, the users returned would be indeterminate and could even change from call to call. The only scenario in which this behavior would be acceptable for the caller is when the `filter` argument is expected to yield at most a single user. In this case, the ordering is not significant. However, even in this situation, specifying an order would not pose any problem for the caller or the implementation. Therefore, we could make the `order' parameter mandatory.

**Comment by zapateo** [comment]
> @zapateo As the method always returns a limited number of users, meaning it may not return all of them, if the caller does not specify an ordering, the users returned would be indeterminate and could even change from call to call. The only scenario in which this behavior would be acceptable for the caller is when the `filter` argument is expected to yield at most a single user. In this case, the ordering is not significant. However, even in this situation, specifying an order would not pose any problem for the caller or the implementation. Therefore, we could make the `order' parameter mandatory.

Yes, seems reasonable.

**Comment by zapateo** [comment]
See https://github.com/open2b/chichi/pull/449.
