### ISSUE TITLE
export: remove the `readUsersFromDataWarehouse` function and improve export

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#412]
The function `readUsersFromDataWarehouse` is deprecated and it can export at most 1000 users (see the issue https://github.com/open2b/chichi/issues/176, which has been closed in favour of this).

After the merge of the PR https://github.com/open2b/chichi/pull/399, we should remove that function and integrate its content in the code that performs the export.

**Comment by gazerro** [comment]
The pull request open2b/meergo#447 will remove the `readUsersFromDataWarehouse` function once merged into the main branch.
