### ISSUE TITLE
ui: define, implement and document the behavior of sheets when exporting to files

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#430]
At the moment, the concept of _sheet_ is not clearly defined and implemented when exporting to a file.

For instance, in the case of a CSV file, which does not support sheets, this obviously does not need to be defined.

But what happens in the case of exporting to Excel files? Where is the sheet name taken from? Must the file already exist, contrary to what happens with other types of files?

We need to clarify these points, specify them, and implement accordingly.

**Comment by gazerro** [comment]
The user should have the option to specify the sheet name for export when the connection supports multiple sheets. This is distinct from the import, where the sheet must be chosen from those available in the file.

The UI should validate the sheet name based on the following rules to prevent the API from returning a Bad Request:

* The name must be between 1 and 31 characters.
* It should not start or end with the character "'".
* It should not include any of the following characters: "*", "/", ":", "?", "[", "\\", and "]".
