### ISSUE TITLE
apis: review PostgreSQL's case sensitive queries

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#452]
Given the following SQL query:

```SQL
SELECT FROM members WHERE email = 'foo@example.com'
```

PostgreSQL returns only the members that have the given email, with the exact same case.

For instance, if the members table contains a member with email `Foo@example.com`, that user won't be retrieved by the query.

For this reason, we should review the already written queries, to check whether this behavior can cause issues (for example, currently, it's possible to send an invitation to `Foo@example.com` while `foo@example.com` has already been invited).

**Comment by gazerro** [comment]
As discussed with @retini we can create a collation with:

```sql
CREATE COLLATION case_insensitive (provider = icu, locale = 'und-u-ks-level2', deterministic = false);
```

and use it for case-insensitive columns as in:

```sql
CREATE TABLE members (
    organization INTEGER,
    email TEXT NOT NULL COLLATE case_insensitive,
    PRIMARY KEY (organization, email)
);

```
