### ISSUE TITLE
connectors: investigate on value type returned by SnowFlake for VARIANT/Json types

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#453]
According to the file [Data_Types.md](https://github.com/open2b/chichi/blob/59256474b31583c813c5fcc57379e1243b7f976c/apis/connectors/Data_Types.md), the SnowFlake connector returns a `string` value when the column is a `VARIANT`, handled as a JSON type in Meergo.

However, the function `normalizeDatabaseFileProperty` handles the JSON type as if it can only "receive" a `[]byte` value from the driver:

https://github.com/open2b/chichi/blob/da295d95119a3f491a70a1e2aede56570583a129/apis/connectors/normalization.go#L554-L562

So, there is an inconsistency.

Which one is correct? The documentation or the implementation? We need to test this.

**Comment by gazerro** [comment]
The `Query` method of the Snowflake connector returns JSON values as strings. The `normalizeDatabaseFileProperty` function has been replaced by the `normalize` function, which handles both `[]byte` and `string` values.
