### ISSUE TITLE
connectors: terminate storage methods if the operation hangs indefinitely

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#472]
## Steps to reproduce

1. Start an SFTP server (for example using [pyftpdlib](https://pyftpdlib.readthedocs.io/en/latest/index.html#), not sure if this happens with other servers as well)
2. Configure a new destination SFTP connection
3. Test the connection or save it

Chichi hangs forever trying to test the connection. Seems like the problems happens somewhere around:

https://github.com/open2b/chichi/blob/ed7116dd16f070f04cb13007d135ee687637503d/connectors/sftp/sftp.go#L238

**Comment by zapateo** [comment]
The issue seems to be related to the moment when an SSH connection is established with the SFTP server, especially during the handshake when the client and server need to exchange version information (I believe of SSH itself).

**Comment by gazerro** [comment]
This is an issue within the "golang.org/x/crypto/ssh" package. The `ssh.Dial` function becomes blocking when the server fails to send a response. Specifically, in the "transport.go" file at line 344, the call to `io.ReadFull` is causing the blockage:

```go
_, err := io.ReadFull(r, buf[:])
```

This can occur, for instance, if the server does not support the SSH protocol.

**Comment by gazerro** [comment]
If a call to a storage method hangs indefinitely, we should cancel the associated context. For instance, methods within the SFTP connector may experience a hang when connecting to a server, especially if it expects FTP instead of SFTP.
