### ISSUE TITLE
events: consider the addition of the 'gid' property to the events schema

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#476]
Currently, the events schema:

https://github.com/open2b/chichi/blob/5b0c38c66787ea1eb220190f6d0f2aceceffe967/apis/events/schema.go#L15

does not have a `gid` property.

Is there a reason for that? Should it be added? This is related to the properties/columns listed in `eventsMergeTable`, which, in the opposite, declares that property (and with which it may be merged in a single data structure, but this is discussed in https://github.com/open2b/chichi/issues/477).

Note that, currently, when the `Users.Events` is called, we already build a schema which have the properites of `Schema` with the additions of `gid`.

https://github.com/open2b/chichi/blob/3143f37abab69a42a0b066383486764d9bdcffa7/apis/users.go#L60-L67

**Comment by zapateo** [comment]
After a discussion with @gazerro, we have determined that the issue, rather than being logical, is implementational.

I highlight some points from the conversation:

> We understand that the question refers to the types.Type schema of the events we have encoded in the code, not to that used by the implicit mapping, as the "gid" is obviously present in the mapping schema. Whether it should be included or not depends on whether the three uses of types.Type have the same schema or not. It is more of an implementation issue. If the only difference between the three uses is the presence or absence of "gid" in the schema, then evaluate whether it is more convenient to implement it by including it and removing it where not needed or not including it and adding it where needed.

> Logically, I would say that GID should not be usable in anonymous expressions, but it seems that at the moment, for example, we allow userId, so it's strange. I don't know why that part is done in this way. That's why I said I can't draw a conclusion now without first reviewing how the whole thing works.

> So now we allow selecting any property in the types.Type schema of events as an anonymous identifier.

Therefore, before resolving this issue, we need to clarify the matter of anonymous identifiers in the IR (see https://github.com/open2b/chichi/issues/479).

**Comment by gazerro** [comment]
@zapateo Issue open2b/meergo-rewritten#479 has been closed, so we can now continue our discussion of this issue
