### ISSUE TITLE
ui: allow selecting the properties to be available when executing a transformation function

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#507]
## Current situation

In the case of mapping, only the properties referenced in the mapping are included in the input schema of the action.

However, in the case of transformation functions, all properties of the input schema are included in the input schema of the action because we have no way of determining which properties are actually used in the source code of the function.

## 1 - Usage issue

Consider the example of importing events from an app that exposes hundreds of properties.

Even if I use only two or three properties in the transformation function, I find that the action is blocked every time there is a change in any of the hundreds of properties, such as some "custom" property I defined in the app that is not used in the function, making it extremely challenging for users to use transformation functions.

## 2 - Resource waste issue

While it may not be as significant as the first issue, consider again the example of importing events from an app that exposes hundreds of properties. Even if I use only two or three properties in the transformation function, hundreds of unused properties must still be passed to the transformation function each time, which can become costly if the transformation function is remote.

## Possible solution for both issues

We could modify the UI so that, in the full-screen transformation screen, it allows choosing which properties to have available in the transformation function, for example, through a checkbox next to each property in the displayed schema.

> [!NOTE]
> In the case of importing user traits from an event, this solution would not apply to them because the problem does not occur. This is because (1) the event schema never changes, and we wouldn't have the aforementioned problem, and (2) the data savings sent to a transformation function are minimal since the event data is not so relevant in terms of size.

**Comment by gazerro** [comment]
Currently, the `Records` methods in the `connectors` package return values for all properties specified in the action's input schema within the `Record.Properties` field. This includes properties that are not utilized in the transformation. Presently, this is not an issue because the mapping ignores these extra properties, and the function anticipates all properties. 

However, if this proposal is adopted, it would be essential to ensure that only the properties needed by the function are passed to it. Therefore, it would be appropriate for the `Records` methods in the `connectors` package to only include in `Record.Properties` those properties that are actually used in the transformation.

**Comment by gazerro** [comment]
Commit 8fb61d5 has added support for input and output properties. Now, the last step is to implement in the UI the ability to select input and output properties for transformation functions.

**Comment by zapateo** [comment]
After a discussion with @gazerro, we decided that it would be useful to give the user the option to not select any properties initially, meaning that all are passed in/out. This is the simplest case at the beginning, and then the user can choose properties later.

**Comment by zapateo** [comment]
@gazerro, I'm not sure if this is a problem at the moment (for example with some source connectors with many properties) or not. So I'm putting this issue as a "release-blocker" for now, until we can discuss and look into the situation.

**Comment by zapateo** [comment]
After a discussion with @gazerro, we decided this:

## Various Modifications

* [x] Upon opening the transformation screen, show the schemas first, both input and destination (done in https://github.com/open2b/meergo/commit/aa59714b1a6eace2fad63f72e4ddc1e1efa32cfd)
* [x] Reverse both selectors, placing "Schema" before Samples and Result (done in https://github.com/open2b/meergo/commit/aa59714b1a6eace2fad63f72e4ddc1e1efa32cfd)
* [x] The JSON in samples should only show the selected properties, not all
* [ ] The results should also only show the selected properties (this might already be the case?)

## Property Selection

* [x] There should be a checkbox on the right side of each property
* [ ] When a property is not selected, the entire property should be in a light gray
* [ ] When a property is selected, the entire property should change color to something like a light purple
* [x] Unselected objects, for which I have selected a sub-property, should have an Indeterminate checkbox (see the Shoelace Checkbox)

## Popup

* [ ] As soon as I enter in the transformation page for the first time, there should be a popup indicating that I need to select the properties I want
* [ ] The popup should then move to the other schema, the result one, and indicate that properties need to be selected there as well

## Search Bar

There should be a search bar at the top of each property list that contains:

* [x] A text input to search among the properties
* [x] A button that filters the properties, showing only the selected ones
