### ISSUE TITLE
ui: review the arrangement of connection files and storage on the admin's connection screen

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#537]
Review the arrangement of connection files and storage on the admin's connection screen.

In particular, among other things, the arrangement of connections should highlight the fact that each file-type connection is independent of others belonging to the same storage.

**Comment by zapateo** [comment]
Don't do this for now. See https://github.com/open2b/chichi/issues/563.

**Comment by gazerro** [comment]
Close because obsolete.
