### ISSUE TITLE
ui: show the connection identities

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#566]
> [!IMPORTANT]
> ~~This should be done after closing open2b/meergo-rewritten#562.~~ closed

The identities have been exposed by the commit aec086a9eaa16cc10b450c2aa485fead98c0cce0 through the API method:

```
POST /api/workspaces/{id}/connections/{id}/identities
```

**Comment by retini** [comment]
Closed by 51ee74f196eb6760e05a77e85a755c88a7dd80bc
