### ISSUE TITLE
ui: enhance the combobox

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#595]
Enhancements needed for the combobox to improve user experience:

- [x] Ensure the cursor returns to the input field right after the inserted value when an item is selected from the combobox list.
- [x] Reopen the combobox list upon typing new expression fragments, such as function arguments.
- [x] Include a tab for displaying and selecting functions.
- [x] Currently, in rare occasions, if the combobox input is focused and you click outside making it lose focus, for a brief moment the combobox list appears above the input taking the full width of viewport.
- [x] Give, via props, the possibility to show a caret inside the combobox input, to be used when the combobox is used in a way conceptually similar to a select, forcing the user to insert one of the items present in the combobox list and giving an error if a non-existing item is inserted.
- [x] When clicking on a combobox input, the combobox list is opened. If then the cursor is moved over the list in hover, two malfunctions occur that seem to be related: the input loses focus automatically and clicking outside of the combobox no longer closes the combobox list.

**Comment by gazerro** [comment]
@retini Please, review whether any of these modifications to the combobox are critical and must be addressed before the beta release of Meergo. If any are deemed essential, move them to a separate issue labeled 'release-blocker'.

**Comment by retini** [comment]
@gazerro After a review, I found that none of the changes are essential for using the software and therefore none must be considered blocking for the Beta.

**Comment by gazerro** [comment]
@retini Please mark the checkboxes in this issue if all tasks are completed.
