### ISSUE TITLE
proposal: events: detection and exclusion of bots

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#6]
The tracked events should exclusively concern real people browsing the site and not bots. Bots must be identified, and the events they generate must be discarded before they can be added to the event table.**

We can establish three screening phases:

1. The server refuses to serve the tracking script to bots, for example by returning an empty script.
2. The tracking script does not send events for bots.
3. The server discards events generated by bots.

Therefore, bot identification can be done both on the client side by the tracking script and on the server.

### Client

There are several techniques for client-side identification. However, these require additional code to be added to the tracking script, which increases its size and execution times.

Since the server will perform a final screening regardless, on the client side, we will only identify the most common cases, such as benevolent bots easily distinguishable by the user agent. We may also provide support for server-side identification by offering information accessible only on the client side.

## Server

On the server side, we will utilize the [bot detection service](https://developers.cloudflare.com/bots/get-started/pro/) included in CloudFlare's Pro plan.

Additionally or alternatively, we can implement our own detection system ([TLS Fingerprinting with JA3 and JA3S](https://engineering.salesforce.com/tls-fingerprinting-with-ja3-and-ja3s-247362855967/)).

Furthermore, a server-side check should be added to identify anomalies in the event stream from the same device, such as overly frequent event submissions, before sending events to ClickHouse.

**Comment by zapateo** [comment]
@gazerro, why is this issue marked as a 'release-blocker'? Is this a crucial feature for the first beta, or can it be postponed?

**Comment by gazerro** [comment]
@zapateo this could be critical for a production system, but even in this case, I'm not sure if it would fall under Meergo's responsibilities. Therefore, you're right; we can remove the release blocker.

**Comment by zapateo** [comment]
Discussing with @gazerro, we established that the exclusion of bots is something that does not specifically concern Meergo, but should be managed through an external service. Therefore, this issue, in addition to no longer being a 'release-blocker,' no longer has a reason to remain open, as it will not be implemented in Meergo. So I will close it.
