### ISSUE TITLE
ui: cannot save XLSX files with whitespaces in sheet name

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#601]
When loading an XLSX file with a whitespace in the sheet name, when saving the action the error "file does not contain any sheet named ..." is returned.

It looks like it is something related to some transformation that we apply to the sheet name.

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/04e561de-4b3c-45db-b68c-3a5d954ca949)

**Comment by gazerro** [comment]
If the sheet is called "a b", the UI calls the `records` method passing "a_b" as sheet name.
