### ISSUE TITLE
ui: proposal: use more specific names based on connection type and role

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#602]
* [x] Rename "Storage" to "File Storage"

* Change the term "Action" for some combination of connector type/role:

   * Storage/Source and Storage/Destination: rename "Action" to "File"
   * Database/Source: rename "Action" to "Query"
   * Database/Destination: rename "Action" to "Table"

* Change the term "Run now" for some combination of connector type/role:

   * Storage/Source: rename "Run now" to "Import now"
   * Storage/Destination: rename "Run now" to "Export now"

* Change the term "Add" for some combination of connector type/role:

   * Storage/Source and Storage/Destination: rename "Add" to "Add File"
   * Database/Source: rename "Add" to "Add Query"
   * Database/Destination: rename "Add" to "Add Table"
   * All others: rename "Add" to "Add Action"

**Comment by zapateo** [comment]
After a discussion with @gazerro and @retini, we decided that this still needs to be investigated a bit.

**Comment by gazerro** [comment]
Commit a3a45ea has renamed "Storage" to "FileStorage".

**Comment by gazerro** [comment]
At the moment, there isn't a clear idea regarding the other points, so for now it's better to close the issue.
