### ISSUE TITLE
ui: don't allow the selection of the "Excel" timestamp format when non importing from an Excel file

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#609]
From the issue https://github.com/open2b/chichi/issues/606:

> The only difference is that some formats (such as Excel) should not be displayed at the interface level. However, if the APIs (which still allow it) return it as a format for the database, then it should be displayed.

**Comment by gazerro** [comment]
When importing from a non-Excel file or from a database, the UI should not allow the selection of the "Excel" timestamp format.
