### ISSUE TITLE
import: review the re-import, the cursor and the deletions

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#616]
After a discussion with @gazerro (on Tue Jun 11 12:52:29 2024), we decided to:

* [x] Introduce the cursor also for files and databases. Take it from the "last change time" column, if it has been explicitly indicated, because this column is "reliable" (since it has been chosen for identity resolution). For databases, give the possibility to insert a placeholder for the last change time, optionally, if one wants to optimize the query execution. a6ff91a, a40bfc4
* [x] Implement in a general way, in the case in which Chichi gets all the data from the external source, the deletion of identities that no longer exist there.  0c4199a
* [ ] ~Implement an ad hoc procedure for deleting apps and in certain cases databases (if the placeholder on the last change time is in the query).~
* [x] Handle the case where an action transformation is modified. Will the next import need to be a re-import, for the new transformation to be "effective" on the identities? Investigate. e5e8b8d

<details>
<summary>Obsolete</summary>

## The situation

Currently, in the code, we have many references to the "reimport" option, which is somehow related to the concept of the "cursor" for source app connections.

## What to do

We should discuss about this, deciding whether to keep this option and/or the cursor and eventually implement it or remove it.

## Changes related to this

* [apis: delete already imported identities when re-importing from apps](https://github.com/open2b/chichi/commit/e4402f729a5523ca41c64b25327afcdcbde40378)

## Observation (Fri May 24 09:23:22 2024)

We must take into consideration the fact that, for example, for apps, it is possible to have multiple actions each importing with its own filter.

How should the re-import behave?

Because if all identities are deleted, regardless of the action that imported them, in the case of multiple actions with filters, we would have a situation where the execution of one action deletes identities that it itself would not re-import.

## Observation 2 (Mon May 27 11:34:57 2024)

With the current implementation and documentation it is not clear what is guaranteed at the end of the import of an action.

One thing you might expect is that at the end of an action's import, all users who match that action's filters and all properties mapped by that action are updated to reflect what's there (e.g. ) on the remote app.

This would therefore mean reviewing the concept of import and re-import, because currently:

* if I re-import everything from scratch, all the identities are deleted, regardless of which action imported them, and therefore by re-importing I would only have the identities of the current action, not the others
* if I don't reimport but import normally, already imported users would not be updated according to the new mappings/transformations

Maybe one way is to import sequentially from all actions, every time?

## Observation 3 (Tue Jun 11 09:48:32 2024)

The problem of deleting identities imported from an action is no longer difficult, as identities [are now associated with actions instead of connections](https://github.com/open2b/chichi/commit/943e3ef207c4dd72c036046bad1a1b093650d0a0).

</details>

**Comment by gazerro** [comment]
As discussed with @zapateo, we will:

-  Reset the cursor of an action if a transformation is modified. (done in commit f2454e7)
-  Arrange a procedure to remove identities whose corresponding users no longer exist in the app.

**Comment by gazerro** [comment]
> Implement an ad hoc procedure for deleting apps and in certain cases databases (if the placeholder on the last change time is in the query).

For apps, we would need to create a system that reads all the app's external identifiers and then removes any identities not found in that list. This would have to be done for every import that isn't a reimport. This process would be too expensive to carry out. Instead, for apps that support webhooks (which should be most of them), using webhooks to remove outdated identities would be much more effective.

For databases, since it's not possible to run a query that only reads external identifiers without asking the user for a special query, the only solution would be to reread all the rows. This makes it very inefficient when it's not a reimport. Alternatively, we could allow two schedules for databases: one for reimport and one without reimport.

Given this, I consider this issue closed as all other points have been implemented.
