### ISSUE TITLE
connectors: remove `SourceDescription` and `DestinationDescription` from files, file storages, and databases

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#640]
Remove `SourceDescription` and `DestinationDescription` from files, file storages, and databases.

So, it is the responsibility of Chichi to generate the descriptions when the actions types are returned.

Remember to update the documentation under `doc`.

**Comment by gazerro** [comment]
> Remember to update the documentation under doc.

The documentation has been updated by commit 5a69aa9.

**Comment by gazerro** [comment]
Commit 6ddc149 closes this issue.
