### ISSUE TITLE
import: implement `SuggestPropertyName` function to support column names with spaces

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#670]
At the moment, when importing from a file, if the file contains a column with a space in its name, Meergo prevents importing from such a file.

This represents a significant limitation in using file imports, and we should reconsider this.

Probably, it's just a matter of implementing the `SuggestPropertyName` function:

https://github.com/open2b/meergo/blob/7ad56d474f4add83b3472fe334ca051a03fcfb07/connector.go#L52-L60

**Comment by gazerro** [comment]
@zapateo: Probably, it's just a matter of implementing the SuggestPropertyName function

Yes, it is the `SuggestPropertyName` function that has to be implemented.
