### ISSUE TITLE
apis: add the concept of "status" of the data warehouse

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#704]
Add a "POST workspaces/{workspace}/warehouse/status" method that returns the status of the data warehouse.

The possible statuses are:

* "Active": Normal access to the data warehouse.
* "ViewOnly": Write operations are suspended, but reading is allowed, for example, to investigate the warehouse's status, check user statuses, etc.
* "Offline": No user/event read/write queries allowed, but operations to make the warehouse functional (e.g., checks and initializations) can still be performed. Convenient for maintenance.

This is independent of the method that checks the warehouse tables/columns. It could be the UI that, when enabling a warehouse, performs a check first.

The initial status is "Offline".

The various API methods must check the warehouse status and return specific errors.

In the UI, add a sort of select option to choose the status. For now, it's the quickest solution.

**Comment by gazerro** [comment]
This issue has been resolved by commits d1e4966 and 97d4630 regarding the server. For the UI, issue open2b/meergo-rewritten#713 has been opened.
