### ISSUE TITLE
Check (and eventually fix) the endpoint that serves the files under `/javascript-sdk/`

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#716]
Check (and eventually fix) the endpoint that serves the files under `/javascript-sdk/`.

Is this code still correct?

https://github.com/open2b/meergo/blob/47944f89622e7c379e41e1284a0bf73045c56782/cmd/server.go#L177-L178

Does it work even in the case when Meergo is launched within the directory `cmd/meergo` of the repository?

**Comment by zapateo** [comment]
@gazerro can you check this, please?

**Comment by gazerro** [comment]
Commit fe0f3cf resolves this issue.
