### ISSUE TITLE
Review the implementation of the filters and the "where" expressions

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#727]
Some points:

* The "BaseExpr" type has a field "Property string", and this field is treated as a property path by the code that handles filters, while it is treated as a property name by the rest of the code (e.g., by the data warehouse).
* Currently, the "where" expressions allow for expressing more advanced logic compared to filters. What is its purpose? Is it necessary? Should we standardize this behavior?
* Having to implement a conversion from property paths to columns within the datastore, it might make sense to (1) create a "filters" package containing filter code used both by APIs and the datastore, (2) move the "where" definitions into the datastore, (3) ensure that "where" clauses refer to columns rather than properties, so that this transformation can be done directly when transitioning from filters to "where" clauses within the datastore (this cannot be done externally because APIs operate at the property level, not the column level, requiring a transformation before passing "where" clauses to the driver).

**Comment by gazerro** [comment]
The "where" expressions should be able to express SQL conditional expressions, no matter what filters allow.

We can choose how abstract or expressive our filters are without any limits. So, let's hold off on changing how the filters work for now.

Here's what we need to do:

1. Move the filter types to the new `apis/filters` package.
2. Rename the `BaseExpr.Property` field to `Column`.
3. Turn a filter into a "where"  expression in the datastore before sending it to a warehouse.

**Comment by zapateo** [comment]
We've decided that @gazerro will handle the implementation of this issue, but first we need to close open2b/meergo#726.
