### ISSUE TITLE
Check alignment (and investigate about normalization) when reading from the data warehouse

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#728]
Similarly to how we do it when reading from connectors, we need to investigate the alignment between the input schema of export actions (which read data from the warehouse) and the "users" schema currently defined within the workspace.

Additionally, we should consider the normalization aspect and how it should function.

See the references to this issue in the code.

**Comment by zapateo** [comment]
@gazerro, I think this issue can be closed. Do you agree?

**Comment by gazerro** [comment]
@zapateo Currently reading from the data warehouse, alignment assumes that one schema is a subschema of the other. This needs to be changed to behave as in the case of connectors. Therefore, this issue cannot yet be closed.

**Comment by zapateo** [comment]
I'm closing this issue in favor of the meta-issue on alignment checks: https://github.com/open2b/chichi/issues/783.
