### ISSUE TITLE
ui: unhandled unprocessable errors with `FetchSchemaFailed` code

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#737]
In the `add-action-types-endpoint` branch, there are three endpoints that can return an unprocessable error with code `FetchSchemaFailed`:

* GET    /api/workspaces/{workspace}/connections/{connection}/actions/schemas/Events/{eventType}
* GET    /api/workspaces/{workspace}/connections/{connection}/actions/schemas/{target}
* GET    /api/workspaces/{workspace}/connections/{connection}/action-types

**Comment by retini** [comment]
Closing this since we've found that for all three endpoints, the UI is already correctly displaying the error with code `FetchSchemaFailed`.
