### ISSUE TITLE
ui: cannot specify type constraints when creating a new type

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#744]
## The situation

Currently, in the UI for creating properties, it is not possibile to specify type contraints except for those that are mandatory (as the bit size for integer types, for example).

For example, there is no way to choose the maximum character lenght of a Text type, even though the PostgreSQL driver supports it:

![331076351-79bd92cf-e0a3-44f0-b27e-80d047b883f9](https://github.com/open2b/meergo-rewritten/assets/891354/b68a5f2c-79cf-4346-939b-f82513bf2248)

## Relation with the issue open2b/meergo-rewritten#743

This is related to the issue open2b/meergo-rewritten#743, and maybe we should address these things together.

**Comment by retini** [comment]
As discussed with @gazerro and @zapateo, for now we have decided to implement only the maximum character and byte length of Text types.

Additional constraints will be evaluated and possibly implemented with issue open2b/meergo-rewritten#743.
