### ISSUE TITLE
warehouses: deciding how to handle identities when a connection is deleted

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#756]
Should the identities of the connections also be removed from the data warehouse when a connection is deleted? And what should be done if the data warehouse is not in Normal mode or has been disconnected?

In addition, it should be noted that a connection is also deleted when its corresponding workspace is deleted.

**Comment by zapateo** [comment]
That is already the current behavior, so this issue can be closed.

**Comment by gazerro** [comment]
> That is already the current behavior, so this issue can be closed.

@zapateo Are you sure?

**Comment by zapateo** [comment]
> > That is already the current behavior, so this issue can be closed.
> 
> @zapateo Are you sure?

@gazerro 

This code:

https://github.com/open2b/meergo/blob/d93b15efefa2941f01b9c9a9c811d4bb98d9a2a1/apis/datastore/warehouses/postgresql/identity_resolution.go#L34-L51

should handle the deletion of the identities.

In particular:

> Should the identities of the connections also be removed from the data warehouse when a connection is deleted?

This is done in the method `RunIdentityResolution`.

> And what should be done if the data warehouse is not in Normal mode or has been disconnected?

This is related to the Identity Resolution:

https://github.com/open2b/meergo/blob/bbfeb7e5d8126cf68f5a0c2af91fe875fb17eccc/apis/datastore/store.go#L371-L378

> In addition, it should be noted that a connection is also deleted when its corresponding workspace is deleted.

This is handled by this code:

https://github.com/open2b/meergo/blob/bbfeb7e5d8126cf68f5a0c2af91fe875fb17eccc/apis/datastore/store.go#L393-L404

this should be reviewed in relation to the state and to the access of it (should we freeze it?), but if a workspace is deleted and the `RunIdentityResolution` is called, the method returns nil, so this should be already be handled.
