### ISSUE TITLE
Investigate and manage the case where a transformation (mapping or function) wants to discard and/or not update a user's property

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#769]
Investigate and manage the case where a transformation (mapping or function) wants to discard a user and/or not update a user's property

## Points to explore and manage

* [x] Verify the behavior for mappings. What happens if all expressions return void? Is there a way to simplify this, to communicate not to import a user, without having to handle it individually in each mapping? Does it make sense?
* [x] If the transformation function in Python returns `None`, an error is returned, whereas it could be useful for the user not to be imported.
* [x] Verify the behavior for transformation functions in JavaScript.
* [x] Check what happens if the transformation function returns an empty object. What is imported? For which user?
* [x] In general, transformations (both mappings and functions) must be express: (1) a specific value (2) the fact that a value must be set to NULL (3) the fact that a value should not be updated, as it is unknown. What is the current situation?
* [x] Currently, mappings can return a 'void' value. Can functions do this as well? Should we rename 'void' to 'unknown' to indicate that the value should not be reset/cleared, but rather that it is unknown and therefore should be preserved? Additionally, we should document this in the 'doc'.

**Comment by gazerro** [comment]
> Currently, mappings can return a 'void' value. Can functions do this as well? Should we rename 'void' to 'unknown' to indicate that the value should not be reset/cleared, but rather that it is unknown and therefore should be preserved? Additionally, we should document this in the 'doc'.

As discussed with @zapateo, the term 'void' is only used internally within Chichi and does not need to be explicitly documented. The current documentation for the 'when' function is sufficient. Therefore, we will keep the term 'void' as it is.

**Comment by gazerro** [comment]
> Verify the behavior for mappings.

The behavior is correct.

> What happens if all expressions return void?

If all expressions return void the transformation returns an empty map. 

> Is there a way to simplify this, to communicate not to import a user, without having to handle it individually in each mapping? Does it make sense?

By using transformation functions, simply return an empty object. However, for mappings, I don't see a simple solution; in this case, you'll have to exclusively use the action's filters.

**Comment by gazerro** [comment]
> If the transformation function in Python returns None, an error is returned, whereas it could be useful for the user not to be imported.

This is the intended behavior.

> Verify the behavior for transformation functions in JavaScript.

It is the same as Python.

> Check what happens if the transformation function returns an empty object. What is imported? For which user?

During export, the user is not exported (refer to commit c04c209). During import, the user is imported with all properties set to NULL. When receiving an event, if the user is anonymous, it is not imported; otherwise, it is imported with all properties set to NULL.

**Comment by gazerro** [comment]
> In general, transformations (both mappings and functions) must be express: (1) a specific value (2) the fact that a value must be set to NULL (3) the fact that a value should not be updated, as it is unknown. What is the current situation?

A transformation can:

1. specify a specific value for a property.
2. specify `null` for mappings and JavaScript, or `None` for Python.
3. omit the property for functions or use the `when` function for mappings.

**Comment by gazerro** [comment]
@zapateo we can close this issue?

**Comment by zapateo** [comment]
> @zapateo we can close this issue?

I'm not yet certain, some aspects of the situation are still unclear to me. I would wait to implement the changes to the writing of the identities, after which I would check if this issue still suggests something we haven't considered. If not, then I would close it.

**Comment by zapateo** [comment]
@gazerro, considering the recent discussions, it seems that now all the points of this issue have been either implemented, discarded, or reported in other issues. So I'm going to close this one.
