### ISSUE TITLE
doc: consider making the documentation index collapsible and expandable

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#776]
Consider making the documentation index collapsible and expandable.

Since we are starting to have numerous pages, it is sometimes difficult to find the right page from the index, which is always expanded:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/97a415c6-8c55-4b56-88ee-2dc700a56d7f)

One possible solution is to add the following section to the `book.toml` file:

```toml
[output.html.fold]
enable = true
level = 0
```

However, a problem arises with the style we are currently using, which seems to not render correctly:

![image](https://github.com/open2b/meergo-rewritten/assets/11294400/bd1ef971-111c-4d43-a2a7-26fd67a4e474)

Therefore, I propose to:

* evaluate making the sections collapsible
* if so, fix the style

**Comment by zapateo** [comment]
@gazerro what do you think?

**Comment by gazerro** [comment]
@zapateo yes, it's better for the menu to be initially collapsed and then expandable. mdbook's default solution doesn't convince me. I'll ask @retini what can be done.

**Comment by retini** [comment]
@gazerro, @zapateo, you can refer to PR open2b/meergo#779 to test the menu improvements.
