### ISSUE TITLE
Decide whether anonymous users should be stored together with others

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#778]
We currently keep anonymous users together with non-anonymous users, both in the `users_identities` and in the `users` tables.

We need to decide whether this is the desired behavior, or whether to keep anonymous users separate from others.

Separating them would be a significant change, which would impact different parts of the software, from the UI to the API, up to the warehouse tables and their use (for example, in the context of data analysis).

**Comment by gazerro** [comment]
@zapateo can we resolve this issue by concluding that anonymous users are retained alongside non-anonymous users?

**Comment by zapateo** [comment]
> @zapateo can we resolve this issue by concluding that anonymous users are retained alongside non-anonymous users?

Yes I agree. I'm closing this.
