### ISSUE TITLE
Remove void from mappings and return error if a transformation (mapping or function) does not return all properties

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#784]
After discussing with @gazerro, we decided to:

1. Remove void from mappings
2. Return error if a transformation (mapping or function) does not return all properties

This is because there doesn't appear to be a use case in which a user decides not to provide the value for a property that they are mapping.

Note that these two changes are linked to each other, and therefore it is likely that they will need to be implemented together.

**Comment by zapateo** [comment]
@gazerro, what did we finally decide about this?

**Comment by zapateo** [comment]
After a discussion with @gazerro, we decided to revisit this issue later. It shouldn't cause anything major for now, so we'll think about it again later during a "cleanup" phase.

**Comment by gazerro** [comment]
This issue has been split into two separate issues: open2b/meergo-rewritten#840 and open2b/meergo-rewritten#841.
