### ISSUE TITLE
warehouses: complete the Snowflake data warehouse driver

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#842]
See the list of sub-issues.

**Comment by gazerro** [comment]
When the driver for Snowflake is completed, we also need to conduct tests for issue open2b/meergo-rewritten#767 as indicated in the [related note](https://github.com/open2b/chichi/issues/767#issuecomment-2199712768).

**Comment by zapateo** [comment]
Also, take a look at https://github.com/open2b/meergo-rewritten/issues/1067 and do the same for Snowflake.
