### ISSUE TITLE
apis: should the input schema of actions that dispatch events to apps be invalid?

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#851]
Just as we do for actions that import identities from events, where the input schema is that of the events and therefore, being always the same, is required to be invalid - at the APIs level -, should we do the same thing also for actions that dispatch events to apps?

That is, should this check:

https://github.com/open2b/meergo/blob/7505de289e4c984e1289c384054f51a223c358de/apis/action_validate.go#L73-L82

be extended to actions that dispatch events as well? Or is there something I'm missing?

**Comment by gazerro** [comment]
Yes, it should be the invalid schema.
