### ISSUE TITLE
mapping: provide something to handle null JSON and other similar cases

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#874]
## The Scenario

Let's consider the scenario where a user imports from a JSON file.

Some keys in the JSON file have a value, other keys have 'null' as value.

In a mapping like this (which seems to be reasonable):

* a → a
* b → b

a problem occurs in the case when a property on the left (let's say 'b') has 'null' as value, because 'null' cannot be assigned to 'b' (being it a property of the user schema, which is always non-nullable).

The only solution, in this case, seems to be using the transformation functions.

## What To Do

We should discuss about this and find a solution to handle cases like these, which may be frequent, maybe providing a function / an operator that can be used in the mappings.

**Comment by gazerro** [comment]
@zapateo before commit 5ca6a54, the JSON `null` value in a JSON file was returned by the JSON connector as `nil`. Consequently, the following conversion was applied: [5ca6a54](https://github.com/open2b/chichi/blob/main/apis/transformers/mappings/Conversions.md#handling-of-nil).

After commit 5ca6a54, the JSON `null` value in a JSON file is returned by the JSON connector as the JSON `null` value, but the allowed conversions remain the same as for the `nil` value.

From the Go standard library `json.Unmarshal` documentation:

> The JSON null value unmarshals into an interface, map, pointer, or slice by setting that Go value to nil. Because null is often used in JSON to mean “not present,” unmarshaling a JSON null into any other Go type has no effect on the value and produces no error. 

I propose to use similar behavior:

- If the destination is nullable, JSON `null` is converted to `nil`.
- If it is not nullable, JSON `null` and `nil` are converted to `void`.

However, if the destination has a `JSON` type, this should be discussed as a special case.
