### ISSUE TITLE
Add an option for choosing if automatic JSON deserialization/serialization to/from language specific types should happen in transformation functions

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#877]
Importing from a JSON file like this:

```json
[
    {
        "id": "ff719ab4-c6c9-4a27-8927-9ac30db87d4d",
        "first_name": "Mario",
        "last_name": "Rossi"
    }
]
```

using an action configured like this:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/0820d7fa-5e62-4067-91cc-816a767ab057)

results in a user identity / user with quoted `first_name` and `last_name`:

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/2ecd3acf-fd23-4984-a9d4-430fdb33a7f1)

![immagine](https://github.com/open2b/meergo-rewritten/assets/11294400/43eb1415-c111-4604-9f67-0e1926db0d44)

Why does this happen? What is the expected behavior?

**Comment by gazerro** [comment]
> Why does this happen?

The `first_name` and `last_name` properties are of JSON type. In a Python function transformation, a JSON value is represented as a string containing the JSON code. For instance, the JSON value `"foo"` is represented in Python as `'"foo"'`, and `true` is represented as `'true'`.

In your example, `user["first_name"]` is `'"Mario"'` and `user["last_name"]` is `'"Rossi"'`.

> What is the expected behavior?

This behavior is expected.

**Comment by zapateo** [comment]
After a discussion with @gazerro, we discussed this behavior and decided to make this issue a proposal.

The fact is that the current behavior, where JSON property values ​​are represented in JavaScript/Python as strings, is formally correct but not very intuitive to use.

Proposal:

* add option at function level that says how JSON should behave, both in input and output, on whether an automatic serialization / deserialization in language types should occur
* by default, JSON is deserialized in language types and automatically serialized in JSON by Meergo
* at documentation level, it is simply documented that the language serializer / deserializer is used
* the option could be placed, at UI level, in a sub-menu in the full screen mode of transformations

**Comment by gazerro** [comment]
@zapateo note that if JSON is deserialized into language-specific types, both `nil` and JSON `null` values will be deserialized to `null` in JavaScript and `None` in Python. Therefore, it will become impossible in the function to distinguish between the two cases.

In addition, how would you expect `null` in JavaScript and `None` in Python to be serialized in a nullable JSON property? As `nil` or as the JSON `null` value?
