### ISSUE TITLE
android-sdk: report any changes made to the JavaScript SDK following the discussion on various issues

### ISSUE THREAD

**Issue by retini** [krenalis/krenalis#889]
Currently, there are issues related to the JavaScript SDK that need to be discussed. The eventual subsequent changes to the code should then be reported in this SDK as well. 

Specifically:

- [x] [events: review the usage of autoTrack in the Javascript SDK](https://github.com/open2b/chichi/issues/869)
- [x] [events: cover cases where autoTrack is equal to false after reset method invocation in the tests](https://github.com/open2b/chichi/issues/870)

**Comment by retini** [comment]
Usage of `autoTrack` has been reviewed in the Kotlin SDK, with commit [1f807cf](https://github.com/open2b/analytics-kotlin/commit/1f807cf7b5af2bc28a33d8cbec785908c1c48548).

**Comment by gazerro** [comment]
@retini I have closed the issue open2b/javascript-sdk#5. Is it necessary to check the Android SDK as well?

**Comment by retini** [comment]
@gazerro based on the discussion in issue open2b/javascript-sdk#3, I've updated the Android SDK (commit https://github.com/open2b/analytics-kotlin/commit/31d25bfdc97d066a1273ca840e18b23742e55c15 and commit https://github.com/open2b/analytics-kotlin/commit/3c1c6d2071d6005d8f163a428c797685478eac5c).

Regarding the discussion in issue open2b/javascript-sdk#5, it is not necessary to report any changes in the Android SDK since the behavior of the tests was already the same between the two SDK.
