### ISSUE TITLE
types: `PropertyByPath` function fails to return paths traversing arrays or maps, unlike `Walk` function

### ISSUE THREAD

**Issue by gazerro** [krenalis/krenalis#907]
Currently, the `types.PropertyByPath` function does not return a path if it traverses an array or a map. This behavior is inconsistent with the `Walk` function, which can return paths that `PropertyByPath` cannot.

**Comment by zapateo** [comment]
Note that the issue https://github.com/open2b/meergo-rewritten/issues/911 is related to this.

**Comment by gazerro** [comment]
`types.PropertyByPath` is used in the following places:

* https://github.com/open2b/meergo/blob/d975f0d32df0fb65b84728e01d0fc5937e82feb1/apis/action_validate.go#L524
  `outSchema` is the schema of a destination file action, so it cannot contain property paths that traverse an array or a map.

* https://github.com/open2b/meergo/blob/d975f0d32df0fb65b84728e01d0fc5937e82feb1/apis/filter.go#L60
  `schema` can be any schema. It is expected that the `PropertyByPath` function does not traverse arrays or maps.

* https://github.com/open2b/meergo/blob/d975f0d32df0fb65b84728e01d0fc5937e82feb1/apis/workspace.go#L1900
   `schema` is the user schema, so it cannot contains property paths that traverses an array or a map.

* https://github.com/open2b/meergo/blob/d975f0d32df0fb65b84728e01d0fc5937e82feb1/apis/datastore/store.go#L383-L383
   `ws.UserSchema` is the user schema,  so it cannot contain property paths that traverse an array or a map.

* https://github.com/open2b/meergo/blob/d975f0d32df0fb65b84728e01d0fc5937e82feb1/apis/transformers/mappings/mapping.go#L70
   `outSchema` can be any schema. It is expected that the `PropertyByPath` function does not traverse arrays or maps.

**Comment by gazerro** [comment]
In none of the following cases is it useful or desirable for `PropertyByPath` to return paths that traverse arrays or maps. Therefore, it is preferable to leave the function as it is.
