### ISSUE TITLE
export: make database export consistent according to the use case we want to implement

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#909]
**See the [last comment](https://github.com/open2b/meergo-rewritten/issues/909) for the updated discussion.**

---

Database export can be used in different use cases. This issue collects a series of points needed to make the database export that we have now consistent and complete, that is, the model in which there is already a table, dedicated only to Meergo export, in which Meergo will export by creating, updating and deleting users.

The idea is to see the database export as if it were always in create.

## Some Points

* it is expected that all the columns of the table must have a default, and it is preferable that the default is NULL
* the export must, in case a value is not passed in update, write the default value for that column, so probably the export must be implemented with a merge. Note that the merge must modify all the columns of the table, because the behavior resembles that of files.
* the deletion of rows must also be implemented; to do this, we can read all the users (only the key) in Meergo, or manage everything through a Merge.
* some types of databases do not support Merge, so we need to study specific solutions for those cases
* currently, all properties of a destination database are required. This means that when you export to a database you need to transform on all columns, and this is not something we want. So please review the fact that all columns are required.

## The "ON CONFLICT" Problem (2024/07/16)

When exporting to PostgreSQL, in case when more users (it's not clear how many) have the same value for the choosen key, the PostgreSQL driver / database return an error and this is logged in Meergo:

```
level=ERROR msg="action execution error" msg="ERRORE: Il comando ON CONFLICT DO UPDATE non può influenzare la riga una seconda volta (SQLSTATE 21000)"
```

**Comment by gazerro** [comment]
The use of `ON CONFLICT` is incorrect as it can only be applied to existing unique or exclusion constraints on the table. For instance, the column specified as the key in the action must have a `UNIQUE` constraint.

**Comment by gazerro** [comment]
Summarizing what was discussed with @zapateo:

* For each export, the connector must modify all columns in the table that correspond to the properties of the out schema. The values of columns that are not part of the out schema will not be modified by the export.

* For properties that do not have a value, the connector must ensure that the database sets the default value of the column.

* When reading columns from a table, the connector must set `UpdateRequired` to `true` if the column does not have a default value. (See open2b/meergo-rewritten#997)

* When creating or updating an action, Meergo must verify that the property used as the table key has `UpdateRequired` set to `true` and `Nullable` set to `false`. (See open2b/meergo#996)

Note that the PostgreSQL connector uses `ON CONFLICT (key)`, and therefore requires that `key` is a table key or has a `UNIQUE` constraint. The requirement that the property used as the table key in Meergo must also be a table key in the database is not something we are requesting; hence, this would be a limitation of the connector. However, we reserve the possibility of introducing a preliminary check in Meergo in Beta2, which would also involve modifying the connector's `Column` method by renaming it to `Table` and ensuring it returns key information. (See open2b/meergo-rewritten#993).

Also note that a decision needs to be made on what to do if a column name is not a valid property name or if the type is not supported by Meergo.

**Comment by gazerro** [comment]
This issue has been closed, but the following issues have been opened and can be resolved after Beta1:

* https://github.com/open2b/meergo-rewritten/issues/993
* https://github.com/open2b/meergo-rewritten/issues/997
