### ISSUE TITLE
export: unexpected validation error when transforming samples

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#913]
### Steps To Reproduce

1. Create a user schema with the properties specified in the file "test/example_user_schema.json"
1. Add a Dummy source connection
1. Import from Dummy the users with the "email", "first_name" and "last_name" properties
1. Add a Dummy destination connection
1. Open the screen to add an action that exports users to Dummy
1. Choose some matching properties (eg. "email" on both sides)
1. Select the transformation function (e.g. Python)
1. Open the "testing mode"
1. Write a transformation function that maps "first_name" to "first_name"
1. Run one of the samples

### Expected Behavior

The resulting user is shown, which should only have the "first_name" property

### Encountered Behavior

An error is shown: «data does not validate against the input schema: non nullable property "data.dummy_id" is missing»

![immagine](https://github.com/user-attachments/assets/1a8c9476-6a9f-4878-a3b0-44f98fdf0359)

**Comment by zapateo** [comment]
@gazerro can you take a look at this?

**Comment by gazerro** [comment]
This issue has been resolved by commit db2374f.
