### ISSUE TITLE
ui: samples not available when importing users from events

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#919]
This is similar to the issue https://github.com/open2b/meergo-rewritten/issues/875, which has been resolved.

This, instead, is related to the testing mode when importing users from events.

![image](https://github.com/user-attachments/assets/298fe234-4557-4a41-ad3e-745097064067)

**Comment by retini** [comment]
After discussion with @gazerro and @zapateo, I have paused work on fixing this UI issue as the problem requires further investigation on the server side.
