### ISSUE TITLE
ui: modify the UI to support the new behavior of export to apps

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#934]
> [!IMPORTANT]
> Address this only when open2b/meergo#910 is merged.

Modify the UI to support the new behavior of export to apps.

Various points (some may already be partially/totally implemented):

* [x] If the chosen mode is Create or Create+Update, the action's output schema must also contain the external matching property (the one of the "writing" schema, i.e. the one that already belongs to the out schema)
* [x] In the list of internal and external properties, there must be only those with kind Int, Uint, UUID and Text
* [x] If the chosen mode is Create or Create+Update, i.e. if the mode involves the creation of new users, it is necessary to further filter the external matching properties including only those that (1) appear both in the matching properties schema and in the output schema of the transformation returned by the server, i.e. that are therefore writable and (2) that have the same kind between them
* [x] The property chosen as external matching property cannot be mapped in the mappings, so it must not appear in the transformation UI at all.
* [ ] How to handle the case in which it is the only property of the app's users schema? This is somehow related to open2b/meergo-rewritten#933.
* [x] The property chosen as external matching property cannot be transformed by transformation functions. This is discussed in issue open2b/meergo-rewritten#507 and is somehow related to open2b/meergo-rewritten#933.

**Comment by retini** [comment]
All the tasks have been addressed.

For task `How to handle the case in which it is the only property of the app's users schema?` refer to issue open2b/meergo-rewritten#933.
