### ISSUE TITLE
ui: errors reported in Python transformation function when running a samples are kept when switching to JavaScript

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#947]
## How To Reproduce

* (1) Add a Dummy source connection
* (2) Open the page for creating an action
* (3) Switch to Python
* (4) Open the testing mode
* (5) Write a transformation function that contains a syntax error, for example:

```python
def transform(user: dict) -> dict:
	return {{{
```

* (6) Run a sample: you should now see a syntax error. That is the expected behavior.
* (7) Exit the testing mode
* (8) Switch to JavaScript
* (9) Open again the testing mode

Now, intead of seeing an empty output message, this is shown instead:

![immagine](https://github.com/user-attachments/assets/73888a7e-6d52-4fb8-b9e2-2f19e53e52c3)

which is the syntax error that occurred in Python and that has been preserved here in JavaScript.

**Comment by gazerro** [comment]
Note that the result should persist if the Testing Mode screen is closed and reopened, provided that the transformation type remains the same.
