### ISSUE TITLE
ui: change the UI for creating user schema properties according to `apis/datastore/README.md`

### ISSUE THREAD

**Issue by zapateo** [krenalis/krenalis#951]
This issue is to review the UI that handles user schema properties, to ensure that all and only `types.Type` declared in the `types.Type` column of the `apis/datastore/README.md` table are handled correctly.

**Comment by retini** [comment]
The "Real" constraint has been implemented with commit fbfbf1c.

The only remaining inconsistency between the UI and the specification in `apis/datastore/README.md` is that currently the UI is not showing the range constraints for the numeric types. 

We have decided to postpone the implementation of those constraints, as discussed in issue open2b/meergo-rewritten#956.
